Project\ManagerBundle\Entity\Document:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        description:
            type: text


    lifecycleCallbacks: {  }
