Project\ManagerBundle\Entity\Role:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            columnDefinition: ENUM ('Developpeur','Integrateur','Testeur','designer')

        description:
            type: text



    lifecycleCallbacks: {  }
