Project\ManagerBundle\Entity\Task:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        type:
            type: string
            lenght: 255
            columnDefinition: ENUM ('DEV','Testeur','Integrateur')



    lifecycleCallbacks: {  }
