Project\ManagerBundle\Entity\UserAffectation:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateAffectation:
            type: datetime

    manyToOne:
        project:
               targetEntity: Project
               inversedBy: affectations
               joinColumn:
                  name: project_id
                  referencedColumnName: id
    lifecycleCallbacks: {  }
